name: proyecto3_conduit
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  conduit: ^4.3.7
  conduit_core: ^4.3.6
  conduit_postgresql: ^4.4.0

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^4.3.6
